version: '3.8'

services:
  postgres:
    image: 'postgres'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'company-case'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'user'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
